import React, { useEffect, useRef, useState } from "react";
import maplibregl from "maplibre-gl";
import { Protocol } from "pmtiles";
import "maplibre-gl/dist/maplibre-gl.css";

// Sequential yellow-orange-red ramp (ColorBrewer YlOrRd 7-class) — low rates
// cool yellow, high rates deep red. Domain: south-central TX nominal rates,
// %/year (floor lowered from 1.3 to 1.0 for the low-tax Hill Country counties).
const RATE_STOPS = [
  [1.0, "#ffffb2"],
  [1.27, "#fed976"],
  [1.53, "#feb24c"],
  [1.8, "#fd8d3c"],
  [2.07, "#fc4e2a"],
  [2.33, "#e31a1c"],
  [2.6, "#b10026"],
];
const rateColor = ["interpolate", ["linear"], ["get", "rate"], ...RATE_STOPS.flat()];

const fmtUSD = (n) =>
  n?.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }) ?? "—";

const fmtAcres = (ac) => {
  const n = Number(ac);
  if (!Number.isFinite(n) || n <= 0) return "—";
  return n < 1
    ? `${n.toFixed(2)} ac (${Math.round(n * 43560).toLocaleString()} sq ft)`
    : `${n.toFixed(2)} ac`;
};

const NO_SELECTION = ["==", ["get", "id"], "__none__"];

// City-name normalization matching the pipeline's norm_city (build_region.py),
// so a parcel's TIGER city name keys into rate-breakdown.json's city rates.
const normCity = (name) =>
  (name || "")
    .trim()
    .toLowerCase()
    .replace(/^(city|town|village) of /, "")
    .replace(/-/g, " ")
    .replace(/\s+/g, " ");

// Itemized jurisdiction breakdown from the tile props + rate-breakdown.json.
// Returns rows [{label, rate}] whose rates sum to the parcel's total, or null
// if the county isn't in the breakdown table.
const jurisdictionRows = (p) => {
  const b = RATE_BREAKDOWN[p.cty];
  if (!b) return null;
  const rows = b.base_units.map((u) => ({ label: u.name, rate: u.rate }));
  if (p.cj) {
    const city = b.cities[normCity(p.cj)];
    if (city && city.rate > 0) rows.push({ label: `City of ${city.name}`, rate: city.rate });
  }
  const isdr = Number(p.isdr ?? 0);
  if (isdr > 0 && p.isd) rows.push({ label: p.isd, rate: isdr });
  const sum = rows.reduce((a, r) => a + r.rate, 0);
  // Flag if components don't reconstruct the tile total (partial data): the
  // difference is unattributed special districts not yet itemized.
  const gap = Number(p.rate) - sum;
  return { rows, gap: Math.abs(gap) >= 0.005 ? gap : 0 };
};

const cadHref = (p) => {
  const c = CAD_LINKS[p.cty];
  if (!c) return null;
  const url = c.q && p.id && p.id !== "0" ? c.q.replace("{id}", encodeURIComponent(p.id)) : c.url;
  return { url, name: c.name };
};

// Tiles served from <base>/tiles by default; set VITE_TILES_URL to an external
// host (e.g. R2 custom domain) to serve them elsewhere.
const TILES_BASE =
  import.meta.env.VITE_TILES_URL || `${location.origin}${import.meta.env.BASE_URL}tiles`;

// Parcel tile archives (each under GitHub's 100MB file limit), generated by
// pipeline/build_tiles_region.sh. The first entry (metro-rest) also carries
// the county + ISD overview layers. Suffix keys the per-archive source +
// layer ids; "" is the metro-rest archive.
// Entries are either a bare archive name (served from TILES_BASE) or
// {name, url} for archives hosted elsewhere (overflow tile repos / R2).
import RATE_BREAKDOWN from "./rate-breakdown.json";
import CAD_LINKS from "./cad-links.json";
import ARCHIVES from "./archives.json";
const PARCEL_SOURCES = ARCHIVES.map((entry, i) => [
  i === 0 ? "" : `-${i}`,
  typeof entry === "string" ? entry : entry.name,
  typeof entry === "string" ? null : entry.url,
]);

// Free federal raster services: USGS basemaps + FEMA National Flood Hazard
// Layer (layer 28 = flood hazard zones, drawn via dynamic export tiles).
const USGS_IMAGERY =
  "https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}";
const USGS_TOPO =
  "https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}";
const FEMA_NFHL =
  "https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/export" +
  "?dpi=96&transparent=true&format=png32&layers=show:28" +
  "&bbox={bbox-epsg-3857}&bboxSR=3857&imageSR=3857&size=256,256&f=image";

// ── geodesy helpers (measure tool + lot dimensions) ────────────────────
const R_EARTH_FT = 20902231; // feet
const toRad = (d) => (d * Math.PI) / 180;
const distFt = ([lng1, lat1], [lng2, lat2]) => {
  const dLat = toRad(lat2 - lat1), dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R_EARTH_FT * Math.asin(Math.sqrt(a));
};
const bearingDeg = ([lng1, lat1], [lng2, lat2]) => {
  const y = Math.sin(toRad(lng2 - lng1)) * Math.cos(toRad(lat2));
  const x =
    Math.cos(toRad(lat1)) * Math.sin(toRad(lat2)) -
    Math.sin(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.cos(toRad(lng2 - lng1));
  return ((Math.atan2(y, x) * 180) / Math.PI + 360) % 360;
};
// Spherical polygon area (shoelace on the sphere), square feet.
const areaSqFt = (ring) => {
  if (ring.length < 3) return 0;
  let sum = 0;
  for (let i = 0; i < ring.length; i++) {
    const [lng1, lat1] = ring[i];
    const [lng2, lat2] = ring[(i + 1) % ring.length];
    sum += toRad(lng2 - lng1) * (2 + Math.sin(toRad(lat1)) + Math.sin(toRad(lat2)));
  }
  return Math.abs((sum * R_EARTH_FT * R_EARTH_FT) / 2);
};
const fmtDist = (ft) =>
  ft >= 2640 ? `${(ft / 5280).toFixed(2)} mi` : `${Math.round(ft).toLocaleString()} ft`;
const fmtArea = (sqft) =>
  sqft >= 21780
    ? `${(sqft / 43560).toFixed(2)} ac`
    : `${Math.round(sqft).toLocaleString()} sq ft`;

// Per-side lot dimensions from the parcel's outer ring: merge consecutive
// tile-geometry segments while the bearing stays within tolerance, so a
// straight lot line densified by many vertices reads as one side.
const lotDimensions = (geometry) => {
  let rings = [];
  if (geometry.type === "Polygon") rings = [geometry.coordinates[0]];
  else if (geometry.type === "MultiPolygon")
    rings = geometry.coordinates.map((p) => p[0]);
  if (!rings.length) return null;
  const ring = rings.reduce((a, b) => (areaSqFt(b) > areaSqFt(a) ? b : a));
  const pts = ring.slice(0, -1);
  if (pts.length < 3 || pts.length > 400) return null;
  const angDelta = (x, y) => Math.min(Math.abs(x - y), 360 - Math.abs(x - y));
  const runs = [];
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i], b = pts[(i + 1) % pts.length];
    const d = distFt(a, b);
    if (d <= 0) continue;
    const brg = bearingDeg(a, b);
    const last = runs[runs.length - 1];
    if (last && angDelta(brg, last.brg) < 12) {
      last.d += d;
      last.brg = brg;
    } else {
      runs.push({ d, brg, brg0: brg });
    }
  }
  // A straight side can span the ring's start vertex: merge last run into
  // the first when still collinear.
  if (runs.length > 1 && angDelta(runs[runs.length - 1].brg, runs[0].brg0) < 12) {
    runs[0].d += runs.pop().d;
  }
  const sides = runs.map((r) => r.d).filter((d) => d > 3);
  const perimeter = sides.reduce((a, b) => a + b, 0);
  return { sides, perimeter };
};

// TX school homestead exemptions (2025, post-SB4/SB23): $140,000 general +
// $60,000 additional for over-65/disabled. Toggleable on the card.
const SCHOOL_HS_EXEMPTION = 140000;
const OVER65_SCHOOL_EXEMPTION = 60000;

const measureGeojson = (pts) => ({
  type: "FeatureCollection",
  features: [
    ...(pts.length >= 2
      ? [{ type: "Feature", geometry: { type: "LineString", coordinates: pts }, properties: { kind: "line" } }]
      : []),
    ...(pts.length >= 3
      ? [{ type: "Feature", geometry: { type: "Polygon", coordinates: [[...pts, pts[0]]] }, properties: { kind: "fill" } }]
      : []),
    ...pts.map((p) => ({ type: "Feature", geometry: { type: "Point", coordinates: p }, properties: { kind: "pt" } })),
  ],
});

const buyerEstimate = (price, rate, isdRate, ex = {}) => {
  if (!price || price <= 0) return null;
  if (ex.vet100) return 0;
  let schoolTaxable = price;
  if (ex.homestead) schoolTaxable -= SCHOOL_HS_EXEMPTION;
  if (ex.over65) schoolTaxable -= OVER65_SCHOOL_EXEMPTION;
  // Local-option homestead: up to 20% off taxable value for county/city
  // entities that adopted it (varies by entity — modeled as a flat 20%).
  const nonSchoolTaxable = ex.homestead && ex.localOpt ? price * 0.8 : price;
  const nonSchool = (nonSchoolTaxable * (rate - isdRate)) / 100;
  const school = (Math.max(schoolTaxable, 0) * isdRate) / 100;
  return nonSchool + school;
};

const initialView = () => {
  const q = new URLSearchParams(location.search);
  const lat = parseFloat(q.get("lat")), lng = parseFloat(q.get("lng")), z = parseFloat(q.get("z"));
  if (Number.isFinite(lat) && Number.isFinite(lng)) {
    return { center: [lng, lat], zoom: Number.isFinite(z) ? z : 15 };
  }
  return { center: [-98.4, 29.1], zoom: 6.3 };
};

export default function App() {
  const mapDiv = useRef(null);
  const [status, setStatus] = useState("loading map…");
  const [basemap, setBasemap] = useState("map");
  const [flood, setFlood] = useState(false);
  const [measuring, setMeasuring] = useState(false);
  const [measureText, setMeasureText] = useState(null);
  const mapRef = useRef(null);
  const measureRef = useRef({ on: false, pts: [] });

  // Basemap + flood visibility follow React state once layers exist.
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !map.getLayer("basemap-sat")) return;
    map.setLayoutProperty("basemap-sat", "visibility", basemap === "sat" ? "visible" : "none");
    map.setLayoutProperty("basemap-topo", "visibility", basemap === "topo" ? "visible" : "none");
    // Over imagery, thin the fills so the photo reads through (boundaries +
    // rate tint); darken parcel lines for contrast against the photo.
    const fillOp = basemap === "sat" ? 0.22 : 0.7;
    const aggOp = basemap === "sat" ? 0.35 : 0.6;
    for (const [suffix] of PARCEL_SOURCES) {
      if (map.getLayer(`parcel-fill${suffix}`))
        map.setPaintProperty(`parcel-fill${suffix}`, "fill-opacity", fillOp);
      if (map.getLayer(`parcel-line${suffix}`))
        map.setPaintProperty(`parcel-line${suffix}`, "line-color", basemap === "sat" ? "#f5f2e8" : "#4a4943");
    }
    for (const id of ["county-fill", "isd-fill"]) {
      if (map.getLayer(id)) map.setPaintProperty(id, "fill-opacity", aggOp);
    }
  }, [basemap]);
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !map.getLayer("flood-overlay")) return;
    map.setLayoutProperty("flood-overlay", "visibility", flood ? "visible" : "none");
  }, [flood]);

  const [query, setQuery] = useState("");
  const [suggests, setSuggests] = useState([]);
  const [searchMode, setSearchMode] = useState("address"); // address | owner | id
  const searchAbort = useRef(null);
  const searchTimer = useRef(null);

  // Photon geocoder (free, autocomplete-friendly), biased to Texas' center
  // and clipped to the TX bounding box so suggestions stay in-state.
  const geocodeAddress = (q) => {
    searchAbort.current?.abort();
    const ctrl = new AbortController();
    searchAbort.current = ctrl;
    const url =
      "https://photon.komoot.io/api/?limit=6&lat=31.3&lon=-99.3&bbox=-106.9,25.6,-93.4,36.6&q=" +
      encodeURIComponent(q);
    fetch(url, { signal: ctrl.signal })
      .then((r) => r.json())
      .then((d) => {
        const items = (d.features || [])
          .filter((f) => f.properties.state === "Texas" || !f.properties.state)
          .map((f) => {
            const pr = f.properties;
            const line = [
              [pr.housenumber, pr.street].filter(Boolean).join(" ") || pr.name,
              pr.city,
              pr.state,
            ]
              .filter(Boolean)
              .join(", ");
            return { label: line, center: f.geometry.coordinates };
          });
        setSuggests(items);
      })
      .catch(() => {});
  };

  // Owner / Property-ID lookup over parcels currently loaded in the view
  // (needs parcel zoom). Statewide owner index is a documented next step.
  const searchLoadedParcels = (q, mode) => {
    const map = mapRef.current;
    if (!map || map.getZoom() < 12.5) {
      setSuggests([{ label: "Zoom in to a neighborhood to search owners / IDs", disabled: true }]);
      return;
    }
    const layers = PARCEL_SOURCES.map(([s]) => `parcel-fill${s}`).filter((l) => map.getLayer(l));
    const feats = map.queryRenderedFeatures({ layers });
    const needle = q.toLowerCase();
    const seen = new Set();
    const items = [];
    for (const f of feats) {
      const p = f.properties;
      const hay = mode === "id" ? String(p.id || "") : String(p.own || "").toLowerCase();
      if (hay && (mode === "id" ? hay === q : hay.includes(needle))) {
        const key = `${p.cty}:${p.id}:${p.addr}`;
        if (seen.has(key)) continue;
        seen.add(key);
        items.push({
          label: `${p.own || "—"} · ${p.addr || p.id}`,
          center: f.geometry.type === "Point" ? f.geometry.coordinates : undefined,
          feature: f,
        });
        if (items.length >= 8) break;
      }
    }
    setSuggests(items.length ? items : [{ label: "No matches in view", disabled: true }]);
  };

  const onSearchInput = (v) => {
    setQuery(v);
    clearTimeout(searchTimer.current);
    if (v.trim().length < 3) {
      setSuggests([]);
      return;
    }
    searchTimer.current = setTimeout(() => {
      if (searchMode === "address") geocodeAddress(v.trim());
      else searchLoadedParcels(v.trim(), searchMode);
    }, 250);
  };

  const pickSuggest = (s) => {
    if (s.disabled) return;
    const map = mapRef.current;
    if (s.feature) {
      const c =
        s.feature.geometry.type === "Point"
          ? s.feature.geometry.coordinates
          : s.center;
      if (c) map.flyTo({ center: c, zoom: Math.max(map.getZoom(), 16.5) });
    } else if (s.center) {
      map.flyTo({ center: s.center, zoom: 17 });
    }
    setQuery(s.label);
    setSuggests([]);
  };

  const toggleMeasure = () => {
    const map = mapRef.current;
    const m = measureRef.current;
    m.on = !m.on;
    m.pts = [];
    if (map) {
      map.getSource("measure")?.setData(measureGeojson(m.pts));
      map.getCanvas().style.cursor = m.on ? "crosshair" : "";
    }
    setMeasureText(null);
    setMeasuring(m.on);
  };

  useEffect(() => {
    const protocol = new Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);
    const view = initialView();
    const map = new maplibregl.Map({
      container: mapDiv.current,
      style: "https://tiles.openfreemap.org/styles/positron",
      center: view.center,
      zoom: view.zoom,
      attributionControl: { compact: true },
    });
    map.on("moveend", () => {
      const c = map.getCenter();
      const p = new URLSearchParams(location.search);
      p.set("lat", c.lat.toFixed(5));
      p.set("lng", c.lng.toFixed(5));
      p.set("z", map.getZoom().toFixed(2));
      history.replaceState(null, "", `?${p}`);
    });
    map.addControl(new maplibregl.NavigationControl(), "top-right");
    // Live user location (browser prompts for permission on first use;
    // denial just leaves the control inactive — no crash).
    map.addControl(
      new maplibregl.GeolocateControl({
        positionOptions: { enableHighAccuracy: true },
        trackUserLocation: true,
        showUserLocation: true,
      }),
      "top-right"
    );
    window.__map = map;
    mapRef.current = map;

    map.on("load", () => {
      for (const [suffix, archive, url] of PARCEL_SOURCES) {
        map.addSource(`taxes${suffix}`, {
          type: "vector",
          url: `pmtiles://${url || `${TILES_BASE}/${archive}.pmtiles`}`,
        });
      }

      // Insert beneath the basemap's first symbol layer so street/city labels
      // stay readable above the choropleth.
      const firstSymbol = map.getStyle().layers.find((l) => l.type === "symbol")?.id;

      // Alternate basemaps (raster, hidden until picked) sit under all data
      // layers; positron's labels stay on top for a hybrid look.
      map.addSource("usgs-imagery", { type: "raster", tiles: [USGS_IMAGERY], tileSize: 256, maxzoom: 16 });
      map.addSource("usgs-topo", { type: "raster", tiles: [USGS_TOPO], tileSize: 256, maxzoom: 15 });
      map.addSource("fema-nfhl", { type: "raster", tiles: [FEMA_NFHL], tileSize: 256, minzoom: 9 });
      map.addLayer(
        { id: "basemap-sat", type: "raster", source: "usgs-imagery", layout: { visibility: "none" } },
        firstSymbol
      );
      map.addLayer(
        { id: "basemap-topo", type: "raster", source: "usgs-topo", layout: { visibility: "none" } },
        firstSymbol
      );

      map.addLayer(
        {
          id: "county-fill",
          type: "fill",
          source: "taxes",
          "source-layer": "county",
          maxzoom: 7.5,
          paint: { "fill-color": rateColor, "fill-opacity": 0.6 },
        },
        firstSymbol
      );
      map.addLayer(
        {
          id: "county-line",
          type: "line",
          source: "taxes",
          "source-layer": "county",
          maxzoom: 7.5,
          paint: { "line-color": "#fcfcfb", "line-width": 1.5 },
        },
        firstSymbol
      );
      map.addLayer(
        {
          id: "isd-fill",
          type: "fill",
          source: "taxes",
          "source-layer": "isd",
          minzoom: 7.5,
          maxzoom: 13,
          paint: { "fill-color": rateColor, "fill-opacity": 0.6 },
        },
        firstSymbol
      );
      map.addLayer(
        {
          id: "isd-line",
          type: "line",
          source: "taxes",
          "source-layer": "isd",
          minzoom: 7.5,
          maxzoom: 13,
          paint: { "line-color": "#fcfcfb", "line-width": 1.2 },
        },
        firstSymbol
      );
      for (const [suffix] of PARCEL_SOURCES) {
        const src = `taxes${suffix}`;
        map.addLayer(
          {
            id: `parcel-fill${suffix}`,
            type: "fill",
            source: src,
            "source-layer": "parcels",
            minzoom: 13,
            paint: { "fill-color": rateColor, "fill-opacity": 0.7 },
          },
          firstSymbol
        );
        map.addLayer(
          {
            id: `parcel-line${suffix}`,
            type: "line",
            source: src,
            "source-layer": "parcels",
            minzoom: 13,
            paint: {
              "line-color": "#4a4943",
              "line-width": ["interpolate", ["linear"], ["zoom"], 13, 0.3, 15, 0.75, 17, 1.5],
              "line-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0.35, 16, 0.8],
            },
          },
          firstSymbol
        );
        map.addLayer(
          {
            id: `parcel-selected${suffix}`,
            type: "line",
            source: src,
            "source-layer": "parcels",
            minzoom: 13,
            filter: NO_SELECTION,
            paint: {
              "line-color": "#1849c6",
              "line-width": 3,
              "line-opacity": 0.95,
            },
          },
          firstSymbol
        );
        // Red boundary trace on hover (feature-state driven).
        map.addLayer(
          {
            id: `parcel-hover${suffix}`,
            type: "line",
            source: src,
            "source-layer": "parcels",
            minzoom: 13,
            paint: {
              "line-color": "#e0201d",
              "line-width": 2.5,
              "line-opacity": ["case", ["boolean", ["feature-state", "hover"], false], 1, 0],
            },
          },
          firstSymbol
        );
      }

      // Flood overlay above parcel fills (visible at parcel zooms), below labels.
      map.addLayer(
        {
          id: "flood-overlay",
          type: "raster",
          source: "fema-nfhl",
          layout: { visibility: "none" },
          paint: { "raster-opacity": 0.55 },
        },
        firstSymbol
      );

      // Measure tool overlay.
      map.addSource("measure", { type: "geojson", data: measureGeojson([]) });
      map.addLayer({
        id: "measure-fill", type: "fill", source: "measure",
        filter: ["==", ["get", "kind"], "fill"],
        paint: { "fill-color": "#184f95", "fill-opacity": 0.14 },
      });
      map.addLayer({
        id: "measure-line", type: "line", source: "measure",
        filter: ["==", ["get", "kind"], "line"],
        paint: { "line-color": "#184f95", "line-width": 2.5, "line-dasharray": [1.6, 1.2] },
      });
      map.addLayer({
        id: "measure-pts", type: "circle", source: "measure",
        filter: ["==", ["get", "kind"], "pt"],
        paint: { "circle-radius": 4.5, "circle-color": "#184f95", "circle-stroke-color": "#fff", "circle-stroke-width": 1.5 },
      });

      let hovered = null;
      const clearHover = () => {
        if (hovered) {
          map.setFeatureState(hovered, { hover: false });
          hovered = null;
        }
      };
      const onParcelHover = (e) => {
        if (measureRef.current.on) return;
        const f = e.features[0];
        if (hovered && hovered.source === f.source && hovered.id === f.id) return;
        clearHover();
        hovered = { source: f.source, sourceLayer: "parcels", id: f.id };
        map.setFeatureState(hovered, { hover: true });
      };

      const onMeasureClick = (e) => {
        const m = measureRef.current;
        if (!m.on) return;
        m.pts = [...m.pts, [e.lngLat.lng, e.lngLat.lat]];
        map.getSource("measure").setData(measureGeojson(m.pts));
        let text = null;
        if (m.pts.length >= 2) {
          let d = 0;
          for (let i = 1; i < m.pts.length; i++) d += distFt(m.pts[i - 1], m.pts[i]);
          text = `Distance: ${fmtDist(d)}`;
          if (m.pts.length >= 3) text += ` · Area: ${fmtArea(areaSqFt(m.pts))}`;
        }
        setMeasureText(text || "Click to add points");
      };
      map.on("click", onMeasureClick);
      const setSelection = (filter) => {
        for (const [suffix] of PARCEL_SOURCES) map.setFilter(`parcel-selected${suffix}`, filter);
      };

      const onParcelClick = (e) => {
        if (measureRef.current.on) return;
        const p = e.features[0].properties;
        const est = p.mkt > 0 ? (p.mkt * p.rate) / 100 : null;
        const defaultPrice = p.mkt > 0 ? p.mkt : 300000;
        const dims = lotDimensions(e.features[0].geometry);
        const dimsRow = dims && dims.sides.length >= 3 && dims.sides.length <= 8
          ? `<tr><td>Lot dimensions</td><td>${dims.sides.map((s) => Math.round(s)).join(" × ")} ft</td></tr>
             <tr><td>Perimeter</td><td>≈ ${fmtDist(dims.perimeter)}</td></tr>`
          : dims
            ? `<tr><td>Perimeter</td><td>≈ ${fmtDist(dims.perimeter)} (${dims.sides.length} sides)</td></tr>`
            : "";
        const jur = jurisdictionRows(p);
        const jurHtml = jur
          ? `<details class="breakdown"><summary>Jurisdiction breakdown</summary>
               <table class="breakdown-table">
                 ${jur.rows
                   .map((r) => `<tr><td>${r.label}</td><td>${r.rate.toFixed(4)}%</td></tr>`)
                   .join("")}
                 ${jur.gap
                   ? `<tr class="gap"><td>Other special districts</td><td>${jur.gap.toFixed(4)}%</td></tr>`
                   : ""}
                 <tr class="total"><td>Total</td><td>${Number(p.rate).toFixed(4)}%</td></tr>
               </table></details>`
          : "";
        const cad = cadHref(p);
        const cadHtml = cad
          ? `<a class="cad-link" href="${cad.url}" target="_blank" rel="noopener">View on ${cad.name} ↗</a>`
          : "";
        const popup = new maplibregl.Popup({ maxWidth: "340px" })
          .setLngLat(e.lngLat)
          .setHTML(
            `<div class="card">
              <div class="card-addr">${p.addr || "(no situs address)"}</div>
              <div class="card-rate">${Number(p.rate).toFixed(4)}%<span> nominal rate</span></div>
              <table>
                <tr><td>Owner</td><td>${p.own || "—"}</td></tr>
                <tr><td>Lot size</td><td>${fmtAcres(p.ac)}</td></tr>
                ${dimsRow}
                <tr><td>Market value</td><td>${fmtUSD(p.mkt)}</td></tr>
                <tr><td>Est. annual tax</td><td>${est ? fmtUSD(est) : "—"}</td></tr>
                <tr><td>School district</td><td>${p.isd || "—"}</td></tr>
                <tr><td>City</td><td>${p.cj || "Unincorporated"}</td></tr>
                <tr><td>County</td><td>${p.cty}</td></tr>
                <tr><td>Property ID</td><td>${p.id && p.id !== "0" ? p.id : "—"}</td></tr>
              </table>
              <div class="buyer">
                <div class="buyer-title">Buyer estimate</div>
                <label>If purchased at $<input type="text" inputmode="numeric" class="buyer-price" value="${defaultPrice.toLocaleString("en-US")}"></label>
                <div class="buyer-ex">
                  <label><input type="checkbox" class="ex-homestead" checked> Homestead ($140k school)</label>
                  <label><input type="checkbox" class="ex-over65"> Over-65 / disabled (+$60k school)</label>
                  <label><input type="checkbox" class="ex-localopt"> Local-option 20% (county/city)</label>
                  <label><input type="checkbox" class="ex-vet"> 100% disabled veteran</label>
                </div>
                <div class="buyer-result"></div>
                <div class="card-note">Exemption amounts are statewide defaults; local adoption varies by entity</div>
              </div>
              ${jurHtml}
              ${cadHtml}
              <div class="card-note">v0: county-wide + city + ISD units; special districts pending roll data</div>
            </div>`
          )
          .addTo(map);
        const el = popup.getElement();
        const input = el.querySelector(".buyer-price");
        const result = el.querySelector(".buyer-result");
        const exBoxes = {
          homestead: el.querySelector(".ex-homestead"),
          over65: el.querySelector(".ex-over65"),
          localOpt: el.querySelector(".ex-localopt"),
          vet100: el.querySelector(".ex-vet"),
        };
        const update = () => {
          const price = Number(input.value.replace(/[^0-9]/g, ""));
          const ex = Object.fromEntries(Object.entries(exBoxes).map(([k, box]) => [k, box.checked]));
          const b = buyerEstimate(price, Number(p.rate), Number(p.isdr ?? 0), ex);
          result.textContent = b != null ? `≈ ${fmtUSD(b)} / year (${fmtUSD(b / 12)}/mo)` : "—";
        };
        input.addEventListener("input", update);
        for (const box of Object.values(exBoxes)) box.addEventListener("change", update);
        update();
        // Prop_ID '0' means the CAD shared no id (much of Travis): an id-based
        // outline would light up every such parcel in the county, so skip it.
        if (p.id && p.id !== "0") {
          setSelection(["all", ["==", ["get", "id"], p.id], ["==", ["get", "cty"], p.cty]]);
        } else {
          setSelection(NO_SELECTION);
        }
        popup.on("close", () => setSelection(NO_SELECTION));
      };
      for (const [suffix] of PARCEL_SOURCES) map.on("click", `parcel-fill${suffix}`, onParcelClick);
      const aggregateCard = (label) => (e) => {
        const p = e.features[0].properties;
        new maplibregl.Popup({ maxWidth: "300px" })
          .setLngLat(e.lngLat)
          .setHTML(
            `<div class="card">
              <div class="card-addr">${p.name}${label}</div>
              <div class="card-rate">${Number(p.rate).toFixed(4)}%<span> median rate</span></div>
              <table>
                <tr><td>Parcels</td><td>${Number(p.parcels).toLocaleString()}</td></tr>
                <tr><td>Median value</td><td>${fmtUSD(p.med_value)}</td></tr>
              </table>
            </div>`
          )
          .addTo(map);
      };
      map.on("click", "isd-fill", (e) => {
        if (map.getZoom() >= 13) return;
        aggregateCard("")(e);
      });
      map.on("click", "county-fill", aggregateCard(" County"));
      for (const id of [...PARCEL_SOURCES.map(([s]) => `parcel-fill${s}`), "isd-fill", "county-fill"]) {
        map.on("mouseenter", id, () => {
          if (!measureRef.current.on) map.getCanvas().style.cursor = "pointer";
        });
        map.on("mouseleave", id, () => {
          if (!measureRef.current.on) map.getCanvas().style.cursor = "";
        });
      }
      for (const [suffix] of PARCEL_SOURCES) {
        map.on("mousemove", `parcel-fill${suffix}`, onParcelHover);
        map.on("mouseleave", `parcel-fill${suffix}`, clearHover);
      }
      setStatus(null);
    });
    map.on("error", (e) => {
      console.error("map error", e?.error || e);
    });
    return () => {
      map.remove();
      maplibregl.removeProtocol("pmtiles");
    };
  }, []);

  return (
    <div className="app">
      <div ref={mapDiv} className="map" />
      <header className="topbar">
        <h1>Texas Property Tax Map</h1>
        <span className="badge">v0 · statewide — all 254 counties · 2025 · jurisdictions approximate</span>
        <div className="search">
          <div className="search-modes">
            {[["address", "Address"], ["owner", "Owner"], ["id", "Property ID"]].map(([m, label]) => (
              <button
                key={m}
                className={searchMode === m ? "on" : ""}
                onClick={() => {
                  setSearchMode(m);
                  setQuery("");
                  setSuggests([]);
                }}
              >
                {label}
              </button>
            ))}
          </div>
          <input
            className="search-input"
            value={query}
            placeholder={
              searchMode === "address"
                ? "Search an address…"
                : searchMode === "owner"
                  ? "Owner name (in current view)…"
                  : "Exact property ID (in current view)…"
            }
            onChange={(e) => onSearchInput(e.target.value)}
          />
          {suggests.length > 0 && (
            <ul className="search-results">
              {suggests.map((s, i) => (
                <li
                  key={i}
                  className={s.disabled ? "disabled" : ""}
                  onClick={() => pickSuggest(s)}
                >
                  {s.label}
                </li>
              ))}
            </ul>
          )}
        </div>
      </header>
      <div className="layers-panel">
        <div className="layers-title">Layers</div>
        {[["map", "Map"], ["sat", "Satellite"], ["topo", "Topo"]].map(([v, label]) => (
          <label key={v}>
            <input type="radio" name="basemap" checked={basemap === v} onChange={() => setBasemap(v)} />
            {label}
          </label>
        ))}
        <label className="layers-sep">
          <input type="checkbox" checked={flood} onChange={(e) => setFlood(e.target.checked)} />
          FEMA flood zones
        </label>
        <button className={`measure-btn${measuring ? " on" : ""}`} onClick={toggleMeasure}>
          {measuring ? "✕ Stop measuring" : "📏 Measure"}
        </button>
        {measuring && <div className="measure-readout">{measureText || "Click map to add points"}</div>}
      </div>
      <div className="legend">
        <div className="legend-title">Nominal tax rate (% of value)</div>
        <div
          className="legend-bar"
          style={{ background: `linear-gradient(to right, ${RATE_STOPS.map(([, c]) => c).join(",")})` }}
        />
        <div className="legend-labels">
          <span>{RATE_STOPS[0][0]}%</span>
          <span>{RATE_STOPS[RATE_STOPS.length - 1][0]}%</span>
        </div>
        <div className="legend-hint">Zoom in past the district level to see individual parcels</div>
      </div>
      {status && <div className="status">{status}</div>}
    </div>
  );
}
